DHC Components/objects/Limits_Threshold__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This Custom Setting is used for check limits counts in the org.</description>
    <fields>
        <fullName>Display_All__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Display All</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Display_Name__c</fullName>
        <label>Display Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hard_Threshold__c</fullName>
        <label>Hard Threshold</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Impact_Analysis__c</fullName>
        <label>Impact Analysis</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Limit_Type__c</fullName>
        <label>Limit Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Max_Limit__c</fullName>
        <label>Max Limit</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Measure__c</fullName>
        <label>Measure</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Send_Hard_Threshold_Notification__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Send Hard Threshold Notification?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Send_Soft_Threshold_Notification__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Send Soft Threshold Notification?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Soft_Threshold__c</fullName>
        <label>Soft Threshold</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Switch__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Switch</label>
        <type>Checkbox</type>
    </fields>
    <label>Organization Limits Threshold Setup</label>
</CustomObject>

DHC Components/workflows/classes/DHC_ApexCountBatchTest.cls
@isTest(SeeAllData=false)
private class DHC_ApexCountBatchTest{
    static testMethod void dailyDisplayData(){
        List<Limits_Threshold__c> lst = new List<Limits_Threshold__c>();
        Limits_Threshold__c obj = new Limits_Threshold__c();
        obj.Name='Apex Used';
        obj.Display_Name__c = 'Daily Api Requests';
        obj.Limit_Type__c = 'RunTime Limit';
        obj.Measure__c = 'Identify & optimize Client Applications/Partner Products. If optimization not possible, get the limit extended from Salesforce.';
        obj.Display_All__c = TRUE;
        obj.Send_Soft_Threshold_Notification__c = TRUE;
        obj.Send_Hard_Threshold_Notification__c = TRUE;
        obj.Hard_Threshold__c = 13000;
        obj.Soft_Threshold__c = 1000;
        obj.Max_Limit__c = 15000;
        obj.Switch__c = True; 
        obj.Impact_Analysis__c = 'System Integration(s) Outage.';
        lst.add(obj);
        insert lst;
        DHC_ApexCountScheduler apexscheduledcls = new DHC_ApexCountScheduler();
        apexscheduledcls.execute(null);
        test.startTest();
        DHC_ApexCountBatch apexcls  = new DHC_ApexCountBatch();
        apexcls.execute(null,lst); 
        test.stopTest();
      }
    
    }