DHC Components/objects/Limits_Notification__c.object
<CustomObject>
    <description>This object is used for Org Limit Notification.</description>
    <fields>
        <fullName>Breach_Count__c</fullName>
        <label>Breach Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Component_Name__c</fullName>
        <label>Component Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Display_Name__c</fullName>
        <label>Limit Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Entry_Point__c</fullName>
        <label>Entry Point</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Flow__c</fullName>
        <label>Flow</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Hard_Threshold__c</fullName>
        <label>Hard Threshold</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Impact_Analysis__c</fullName>
        <label>Impact Analysis</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Limit_Type__c</fullName>
        <label>Limit Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Limit_Utilization__c</fullName>
        <label>Limit Utilization</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Max_Limit__c</fullName>
        <label>Max Limit</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Breach Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Send_Hard_Threshold_Notification__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Send Hard Threshold Notification?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Send_Soft_Threshold_Notification__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Send Soft Threshold Notification?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sobject_Name__c</fullName>
        <label>Sobject Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Soft_Threshold__c</fullName>
        <label>Soft Threshold</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>UnquieKey__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>UnquieKey</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Breach Notification</label>
    <nameField>
        <displayFormat>Limit-{0000}</displayFormat>
        <label>Limits Notification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Breach Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DHC Components/workflows/classes/DHC_StaticLimitControllerTest.cls
@isTest(SeeAllData=false)
private class DHC_StaticLimitControllerTest{
   static testMethod void dailyDisplayData(){ 
   
   Limits_Notification__c objlst = new Limits_Notification__c();
   objlst.Breach_Count__c = 1;
   objlst.Priority__c = 'Yellow';
   objlst.Component_Name__c = 'AccountCheck';
   objlst.Entry_Point__c ='Account';
   objlst.Flow__c='Account';
   objlst.Hard_Threshold__c=100;
   objlst.Impact_Analysis__c='Impact';
   objlst.Limit_Type__c='Runtime Limit';    
   objlst.Display_Name__c ='Limit Queries';
   objlst.Limit_Utilization__c=70;
   objlst.Max_Limit__c=150;
   objlst.Send_Hard_Threshold_Notification__c = false;
   objlst.Send_Soft_Threshold_Notification__c= false;
   objlst.Sobject_Name__c ='Account';
   objlst.Soft_Threshold__c=60;
   objlst.UnquieKey__c='Account-AccountCheck-60-getLimitQueries-Yellow';
   insert objlst;
   
   Limits_Notification__c objlst1 = new Limits_Notification__c();
   objlst1.Breach_Count__c = 1;
   objlst1.Priority__c = 'Red';
   objlst1.Component_Name__c = 'AccountCheck';
   objlst1.Entry_Point__c ='Account';
   objlst1.Flow__c='Account';
   objlst1.Hard_Threshold__c=80;
   objlst1.Impact_Analysis__c='Impact';
   objlst1.Limit_Type__c='Runtime Limit';    
   objlst1.Display_Name__c ='Limit Queries';
   objlst1.Limit_Utilization__c=90;
   objlst1.Max_Limit__c=150;
   objlst1.Send_Hard_Threshold_Notification__c = false;
   objlst1.Send_Soft_Threshold_Notification__c= false;
   objlst1.Sobject_Name__c ='Account';
   objlst1.Soft_Threshold__c=60;
   objlst1.UnquieKey__c='Account-AccountCheck-90-getLimitQueries-Red';
   insert objlst1;
   
    DHC_StaticLimitController  obj = new DHC_StaticLimitController();
    obj.onclickRunTime();
    obj.hardLimitChartBySobject();
    obj.hardLimitChartByComponent();
    obj.hardLimitChartByType();
    obj.softLimitChartBySobject();
    obj.softLimitChartByComponent();
    obj.softLimitChartByType();
    obj.hardLimitmethodByType();
    obj.softLimitmethodByType();
    obj.hardLimitmethodBySobject();
    obj.softLimitmethodBySobject();
    obj.hardLimitmethodByComponent();
    obj.softLimitmethodByComponent();
    
    }

}