DHC Components/objects/Limits_Notification__c.object
<CustomObject>
    <description>This object is used for Org Limit Notification.</description>
    <fields>
        <fullName>Component_Name__c</fullName>
        <label>Component Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Display_Name__c</fullName>
        <label>Limit Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Breach__c</fullName>
        <formula>CreatedDate</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>First Breach</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Hard_Threshold__c</fullName>
        <label>Hard Threshold</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Latest_Breach__c</fullName>
        <formula>LastModifiedDate</formula>
        <label>Latest Breach Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Limit_Type__c</fullName>
        <label>Limit Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Limit_Utilization__c</fullName>
        <label>Limit Utilization</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Max_Limit__c</fullName>
        <label>Max Limit</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Measure__c</fullName>
        <label>Action Required</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Breach Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Send_Hard_Threshold_Notification__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Send Hard Threshold Notification?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Send_Soft_Threshold_Notification__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Send Soft Threshold Notification?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sobject_Name__c</fullName>
        <label>Sobject Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Soft_Threshold__c</fullName>
        <label>Soft Threshold</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unit__c</fullName>
        <label>Unit</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Breach Notification</label>
    <nameField>
        <displayFormat>Limit-{0000}</displayFormat>
        <label>Limits Notification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Breach Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DHC Components/classes/DHC_ConRuntimeBreachViewController.cls
public class DHC_ConRuntimeBreachViewController {
    public List<Limits_Notification__c> runTimelimitNotificationList{get; set;}
    public DHC_ConRuntimeBreachViewController()
    {
       runTimelimitNotificationList = new List<Limits_Notification__c>();
       for (Limits_Notification__c ln : [Select id, Name, Measure__c, Priority__c, Component_Name__c, First_Breach__c, Hard_Threshold__c, Latest_Breach__c,
                                         Limit_Type__c, Display_Name__c, Limit_Utilization__c, Max_Limit__c, Send_Hard_Threshold_Notification__c, 
                                         Send_Soft_Threshold_Notification__c, Sobject_Name__c, Soft_Threshold__c, Unit__c from Limits_Notification__c 
                                         where Limit_Type__c = 'Runtime Limit' AND Priority__c !='Green' order by Priority__c,LastModifiedDate desc limit 100])
       {       
           runTimelimitNotificationList.add(ln);
       }
    }
}