DHC Components/objects/Limits_Notification__c.object
<CustomObject>
    <description>This object is used for Org Limit Notification.</description>
    <fields>
        <fullName>Display_Name__c</fullName>
        <label>Limit Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hard_Threshold__c</fullName>
        <label>Hard Threshold</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Impact_Analysis__c</fullName>
        <label>Impact Analysis</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Limit_Type__c</fullName>
        <label>Limit Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Limit_Utilization__c</fullName>
        <label>Limit Utilization</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Max_Limit__c</fullName>
        <label>Max Limit</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Measure__c</fullName>
        <label>Action Required</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Breach Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Soft_Threshold__c</fullName>
        <label>Soft Threshold</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Breach Notification</label>
    <nameField>
        <displayFormat>Limit-{0000}</displayFormat>
        <label>Limits Notification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Breach Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DHC Components/classes/DHC_ConsolidatedBreachViewControllerTest.cls
@isTest(SeeAllData=false)
private class DHC_ConsolidatedBreachViewControllerTest{
    static testMethod void dailyDisplayData(){ 
        Limits_Notification__c obj = new Limits_Notification__c();
        obj.Impact_Analysis__c ='Business Process/Logic interruption.';
        obj.Limit_Type__c ='Daily Limit';
        obj.Display_Name__c ='Streaming Api Concurrent Clients';
        obj.Limit_Utilization__c =12;
        obj.Max_Limit__c =20;
        obj.Soft_Threshold__c =10;
        obj.Measure__c ='Business Team : Please get this limit extended from Salesforce.';
        obj.Hard_Threshold__c =15;
        obj.Priority__c = 'Red';
        insert obj;
        DHC_ConsolidatedBreachViewController con = new DHC_ConsolidatedBreachViewController();
        
    }
     static testMethod void runtimeDisplayData(){ 
        Limits_Notification__c obj = new Limits_Notification__c();
        obj.Limit_Type__c ='Runtime Limit';
        obj.Display_Name__c ='Limit Future Calls';
        obj.Limit_Utilization__c =35;
        obj.Max_Limit__c =50;
        obj.Soft_Threshold__c =30;
       obj.Hard_Threshold__c =35;
        obj.Priority__c = 'Red';
        insert obj;
        //DHC_ConRuntimeBreachViewController con = new DHC_ConRuntimeBreachViewController();
        
    }
}