DHC Components/objects/Limits_Notification__c.object
<CustomObject>
    <description>This object is used for Org Limit Notification.</description>
    <fields>
        <fullName>Display_Name__c</fullName>
        <label>Limit Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hard_Threshold__c</fullName>
        <label>Hard Threshold</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Impact_Analysis__c</fullName>
        <label>Impact Analysis</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Limit_Type__c</fullName>
        <label>Limit Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Limit_Utilization__c</fullName>
        <label>Limit Utilization</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Max_Limit__c</fullName>
        <label>Max Limit</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Measure__c</fullName>
        <label>Action Required</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Breach Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Send_Hard_Threshold_Notification__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Send Hard Threshold Notification?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Send_Soft_Threshold_Notification__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Send Soft Threshold Notification?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Soft_Threshold__c</fullName>
        <label>Soft Threshold</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Breach Notification</label>
    <nameField>
        <displayFormat>Limit-{0000}</displayFormat>
        <label>Limits Notification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Breach Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DHC Components/objects/Limits_Threshold__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This Custom Setting is used for check limits counts in the org.</description>
    <fields>
        <fullName>Display_Name__c</fullName>
        <label>Display Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hard_Threshold__c</fullName>
        <label>Hard Threshold</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Impact_Analysis__c</fullName>
        <label>Impact Analysis</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Limit_Type__c</fullName>
        <label>Limit Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Max_Limit__c</fullName>
        <label>Max Limit</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Measure__c</fullName>
        <label>Measure</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Send_Hard_Threshold_Notification__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Send Hard Threshold Notification?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Send_Soft_Threshold_Notification__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Send Soft Threshold Notification?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Soft_Threshold__c</fullName>
        <label>Soft Threshold</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Organization Limits Threshold Setup</label>
</CustomObject>

DHC Components/workflows/classes/DHC_ApexCountBatch.cls
global class DHC_ApexCountBatch implements Database.Batchable<sObject>,Database.AllowsCallouts 
{
    // Start Method
     global Database.QueryLocator start(Database.BatchableContext BC){
        string query = DHC_ConstantsUtils.DHC_LIMITQUERY ;
        return Database.getQueryLocator(query);
     }
   
     // Execute Logic
     global void execute(Database.BatchableContext BC, List<Limits_Threshold__c> scope){
        List<Limits_Notification__c > listOfNotification = new List<Limits_Notification__c >();
       Limits_Threshold__c limitThreshold = Limits_Threshold__c.getValues(DHC_ConstantsUtils.DHC_APEXUSED);
        set<id> objID = new set<id>();
        for(apexclass obj :[SELECT name,id,body from apexclass]){
            if(obj.body.contains(DHC_ConstantsUtils.DHC_ISTEST)){
                apexclass objnew = new apexclass();
                objnew.id = obj.id;
                objID.add(objnew.id);
            }
        }
        AggregateResult arC =[SELECT Sum(LengthWithoutComments)lcc FROM ApexClass WHERE NamespacePrefix =Null AND ID NOT IN :objID];
        Decimal intCdata =(Decimal)arC.get('lcc');
        AggregateResult arT =[SELECT Sum(LengthWithoutComments)lct FROM ApexTrigger WHERE NamespacePrefix =Null];
        Decimal intTdata =(Decimal)arT.get('lct');
        Integer totalcount = Integer.valueOf(intCdata + intTdata);
        system.debug('totalcount +++'+totalcount);
        Limits_Notification__c notification = new Limits_Notification__c();
        notification.Limit_Type__c = limitThreshold.Limit_Type__c;
        notification.Display_Name__c = limitThreshold.Display_Name__c;
        notification.Max_Limit__c = limitThreshold.Max_Limit__c ;
        notification.Hard_Threshold__c = limitThreshold.Hard_Threshold__c;
        notification.Soft_Threshold__c = limitThreshold.Soft_Threshold__c;
        notification.Impact_Analysis__c = limitThreshold.Impact_Analysis__c;
        notification.Limit_Utilization__c = totalcount;
        notification.Measure__c = limitThreshold.Measure__c;
        notification.Send_Hard_Threshold_Notification__c = limitThreshold.Send_Hard_Threshold_Notification__c;
        notification.Send_Soft_Threshold_Notification__c = limitThreshold.Send_Soft_Threshold_Notification__c;
        if(totalcount >= limitThreshold.Hard_Threshold__c){
        notification.Priority__c = DHC_ConstantsUtils.RED;
        } else if (totalcount  >= limitThreshold.Soft_Threshold__c){
            notification.Priority__c = DHC_ConstantsUtils.YELLOW;
        } else {
            notification.Priority__c = DHC_ConstantsUtils.GREEN;
        }
        listOfNotification.add(notification);
        
        if(!listOfNotification.isEmpty()){
            insert listOfNotification;
        }
   }
      
   global void finish(Database.BatchableContext BC){
   
   }
   
 }